### ISSUE TITLE
Adding a new line on textarea doesn't work with prevent.submit = true

### ISSUE THREAD

**Issue by drselump14** [KazanExpress/vue-simple-suggest#102]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

When using vue-simple-suggest with a textarea,  add new line by using enter key on textarea is not working.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Setup -> vue-simple-suggest & textarea inside a form
2. Add new line inside textarea
3. The newline is not added

## **What is the expected behavior?**

The newline is added

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all]
  - Language: [ES6/7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
https://github.com/KazanExpress/vue-simple-suggest/blob/17416533a315ea0633d6b81e263f35215bb64736/lib/vue-simple-suggest.vue#L231
We should stop adding listener on form tag,  because it polutes textarea.

**Comment by ensisf** [comment]
@drselump14 
There is prop `preventSubmit`. By default it is `true`. You can set it to `false`, what will fix your issue.

**Comment by Raiondesu** [comment]
Hello, @drselump14.
We are now looking into your issue.

@ensisf, as this is a good workaround, it still does not really solve the situation completely.

**Comment by Raiondesu** [comment]
@drselump14, issue #94 states that there's no official support for <textarea> element right now. You could, however, extend the component to achieve desirable functionality.

As this bug is a direct conclusion of issue #94, I'll close this and mark it as duplicate. I'm sure that as we implement a full support for textarea later, this bug will not be present anymore.

**Comment by johannpinson** [comment]
Hey @Raiondesu 

I've got the same issue because I don't use a `textarea` as the input for the auto-complete, but the Vue component is inside a form with other fields like checkbox, select, etc.

But as said @drselump14 the plugin add a large eventListener (cf. `onSubmit`) on the form to detect any `Enter` key event, but it didn't check is the `e.target` or `e.srcElement` is the component itself or from another field.

Any change to fix this bug ?
(Because I cannot add a line break inside a textarea which is inside the form where there is your Vue component).


Thank your for the help!

**Comment by iamoskvin** [comment]
Same issue as johannpinson. Any good workaround?

**Comment by Raiondesu** [comment]
Hello, @johannpinson, @iamoskvin.
Is there a possibility this is fixed in the 1.9.6 update?

**Comment by iamoskvin** [comment]
> Hello, @johannpinson, @iamoskvin.
> Is there a possibility this is fixed in the 1.9.6 update?
Yes, it seems to be fixed in 1.9.6. Thank you.
