### ISSUE TITLE
Vue Tips all over console - events must be in kebab-case to work properly

### ISSUE THREAD

**Issue by lauri911** [KazanExpress/vue-simple-suggest#16]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
Events are in camelCase and Vue tips all over console, for example:
[Vue tip]: Event "showlist" is emitted in component <VueSimpleSuggest> at node_modules/vue-simple-suggest/lib/vue-simple-suggest.vue but the handler is registered for "showList". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "show-list" instead of "showList".

https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

## **What is the expected behavior?**
https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

## **What is the motivation / use case for changing the behavior?**
Use VueJs best practises to avoid problems.
https://vuejs.org/v2/guide/components-custom-events.html#Event-Names

## **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [Last Chrome]
  - Language: [ES6/7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Thank you for very good Select! All other selects around cannot deal with Tab properly, yours can!

**Comment by Raiondesu** [comment]
Hello, @lauri911.
First of all - thank you for using the component. ^_^

About the issue - we are aware of it. I will try to fix it in the next patch tonight.
The issue itself is due to ambiguous behaviour of the `vue-loader` for webpack. We forgot to account for some use cases when testing the component and named events in camelCase, because the before mentioned `vue-loader` allows this kind of code. So thanks for the reminder about the dangers of this.

Docs will be updated accordingly.

Keep us updated on the issue status, please.

P.S. I will post here upon releasing the according patch.

**Comment by Raiondesu** [comment]
Also, next time, please, provide a more descriptive list of steps to reproduce the issue.

**Comment by lauri911** [comment]
Vue Tips are from Vue-Devtools.
In this case reproducing steps were redundant, link to right place in Vue documentation was better :)

**Comment by Raiondesu** [comment]
Patch is on npm.

@lauri911, please, let us know if the issue persists with 1.2.4.
