### ISSUE TITLE
gitignore dist folder

### ISSUE THREAD

**Issue by shrpne** [KazanExpress/vue-simple-suggest#167]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the current behavior?**
Dist folder is published to git

## **What is the expected behavior?**
Gitignore dist folder and remove it from source control

## **What is the motivation / use case for changing the behavior?**
- no merge conflicts, especially good for multiple PRs made at the same time
- cleaner git history
- a bit smaller repository size - faster git clone

The downside is that users can't download dist from github, but they always can use unpkg for this

What do you think about it?

**Comment by kaskar2008** [comment]
It makes sense, but there is a use case for packages being installed from the github repository (not the GPR - Github Package Registry). So if we will exclude dist folder from the repo - all dependants libraries using this method of installing will be out of boat.

@Raiondesu ?

**Comment by Raiondesu** [comment]
I support @kaskar2008 on this. Removing dist means restricting some users from accessing the component in a comfortable way for a questionable benefit.

We didn't experience a problem with merge conflicts in `dist` folder nor did we experience any inconveniences because of its existence.

I get that it would be aesthetically more pleasing to work without the `dist` folder, as it's essentially dead code (for development). But still, so are `docs`, `package-lock.json` and others.

I'm closing this as a proposal for unnecessary change.
