### ISSUE TITLE
Changing the `mode` on-the-fly doesn't affect the v-model immediately

### ISSUE THREAD

**Issue by kaskar2008** [KazanExpress/vue-simple-suggest#40]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

When you change the `mode` - `v-model` doesn't change the value.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Just bind the `mode` into a variable and then change it on the runtime.

## **What is the expected behavior?**

`v-model` should be changed accordingly which `mode` has been selected

## **Please tell us about your environment:**
  
  - Vue version: 2.5.16
  - Lib version: 1.5.4
  - Browser: all
  - Language: all

**Comment by Raiondesu** [comment]
I have no idea what to do with this.

It seems that `v-model` originally was not supposed to be changed at run-time, so all the bindings connected to it do not react properly, because they "do not expect" changes to happen.

Currently, the `v-model`'s value is updated upon the very next event that would trigger it, so the issue is not really that serious.

**Comment by Raiondesu** [comment]
Figured how to fix this, but with a caveat: when a `mode` is changes - we need to emit both `input` and `select` events **twice**. No, `$forceUpdate` does not help. I tried. Two render ticks need to pass in the parent component in order for it to recognize that its child has a different model.

I think this is a relatively small price to pay for reactivity overall...

**Comment by kaskar2008** [comment]
@Raiondesu omg, so convenient 😂
