### ISSUE TITLE
Autocomplete from the most suitable suggestion element?

### ISSUE THREAD

**Issue by kaskar2008** [KazanExpress/vue-simple-suggest#41]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the expected behavior?**

When the suggestions list is not empty - get the rest of the text from the element, that complete the most.

## **What is the motivation / use case for changing the behavior?**

In some cases this type of autocompletion is the most convenient (for example, if the component being used as a search box for some results)

**Comment by Raiondesu** [comment]
@kaskar2008, this is a subject for a minor, I think, because this requires rework of markup & CSS classes.

**Comment by Raiondesu** [comment]
I just thought about all this, and now such a functionality seems wrong to me. Mainly because it's not always useful - the case of suggestions that exclusively begin with the query is not 100% common. Most of the time, the suggestion only **contains** the text that user types.

I can only think of google suggestions in their search bar as an appropriate use-case for this.

As for now, the thing that you request can be (much more easily!) achieved outside the component itself, by using a custom input, somewhat like this:

```html
<vue-simple-suggest v-model="query" ref="autocomplete">
  <overshadow-input :bolden-value="query" :overshadow="$refs.autocomplete.suggestions[0]"/>
</vue-simple-suggest>
```

where `overshadow-input` is an input component that can append a text overshadow and bold a certain part of it.

So the whole thing is not only would add the un-needed internal complexity, but is also more than easily solved outside of the component by a programmer using it.

**Comment by kaskar2008** [comment]
I guess you are right. It was only a proposal tho.
