### ISSUE TITLE
Clear currently selected item.

### ISSUE THREAD

**Issue by kherona** [KazanExpress/vue-simple-suggest#77]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**
I am sorry if this is covered anywhere, but I have been looking for quite sometime to find a way to clear the search text after selecting an item.

this would be great for different use cases, for example if a user search for multiple items in a list, I would like to clear the selected item when they click it and prompt them to search for another item (I would add the selected item on a different list, so no need for multiple select in the input).

## **What is the expected behavior?**
Be able to clear search entry, by either have a button to clear search text on be able to clear it via events.

## **What is the motivation / use case for changing the behavior?**
I am using auto-suggest to allow users to select multiple cities/location, each time they choose one it will be added and they will be prompted to search for another location.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by Raiondesu** [comment]
Thank you for submitting, @kherona.
We'll look into the feature soon. :)

**Comment by Lofbergio** [comment]
Couldn't you do it via the ref method 'select'? https://kazanexpress.github.io/vue-simple-suggest/#ref-methods

Only problem is that if you don't have the options to use $ref.

**Comment by eZawer** [comment]
@Lofbergio I managed to do a few hacks to get this behavior working. for example on select, I would clear the v-model item, and clear the input box, but it would be better to get this behavior by a simple option on the component itself.

**Comment by Lofbergio** [comment]
The issue i guess is that what to do when someone comes along and wants the same functionality but a slight variation, for example don't clear the text.
The functionality is so specific for the scenario and the "hack" is the same inside of the component where we clear the searchQuery after a select event.

I would argue that its much easier to simply wrap this component into your own and put the functionality into the wrap, it also eases further development since the product specific features are there and you dont rely on some external component to implement whatever feature that you need today.

**Comment by kaskar2008** [comment]
@kherona It is very specific feature that depends on a business logic. I'd rather not implement it. At least until we find the way to implement it conveniently.
Closing this issue.
