### ISSUE TITLE
"select" event is sent when clearing input

### ISSUE THREAD

**Issue by robjbrain** [KazanExpress/vue-simple-suggest#93]
## **I'm submitting a ...**
  - [ ] bug report

## **What is the current behavior?**
If you highlight the content of the input and hit "backspace" to clear the input then a "select" event is fired with a `null` payload. I would assume that select would be called only if you actually selected something. So i'm not sure why select is being called here. Entering backspace to clear the input is just typing so it shouldn't be selecting anything.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
You can view a video here: https://www.useloom.com/share/2f336be5796d4fac82fb15996b64b7f4

1) Go to the demo and search for "Helicopter"
2) Select "Helicopter"
3) Press Ctrl+A
4) Press Backspace
5) The a "select" event will be fired.

Oddly if you're typing and "ctrl+a" and then "backspace" a select event won't fire. It's only fired if you do so after a mouse click from what I can tell.

## **What is the expected behavior?**
Select should not fired on a backspace. It says in the docs that select is only fired on "a mouse click or enter keypress".

### How are you importing Vue-simple-suggest?

- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
</script>`)

## **What is the motivation / use case for changing the behavior?**
It's a bug

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.17
  - Vue-simple-suggest version: 1.8.2
  - Browser: Chrome Windows
  - Language: ES6

**Comment by kaskar2008** [comment]
Hi @robjbrain 
Thank you for your good described issue, I appreciate it!
However, this is happening because of the logic of component under the hood. See, `select` event is firing to make the component model contains some selected item information. If there was an item, and you remove all the "search" text - component should clears that selected data, therefore `select` event with `null` as a payload has to be done.

If I understood you correctly, you may close this issue. Otherwise - I'm open to hear I'm wrong :)

**Comment by robjbrain** [comment]
Perhaps it is a naming issue? Right now whenever select is called you have to check if something is selected.

```
<input onSelect="onSelect" />

onSelect(selected) {
    if (selected !== null) {
        // do your logic with the selected item
    }
}
```

This seems like un-necessary logic to add to every single use.

Surely select should only be fired if something is actually selected?

Maybe there should be a "cleared" or "reset" event rather than use the select event?

Or even better you could have two events:
select: whenever an item is selected
change: whenever the item is changed (including being reset to null)

**Comment by kaskar2008** [comment]
> select: whenever an item is selected
> change: whenever the item is changed (including being reset to null)

Actually, the idea of `change` event is good. But instead of one missleading name for the event - we will get two xD

**Comment by robjbrain** [comment]
onUpdate?

**Comment by kaskar2008** [comment]
@Raiondesu?

**Comment by Raiondesu** [comment]
Well... there's *some insight* for you:

The logic behind "deselecting" an item when you erase the input is pretty simple: when nothing is in the input - nothing is selected. In other words, if one changes the input contents - its likely that one wants to select something else. Therefore - the `select` event, that is also the `deselect` event.

`selected === null` is the first state of the component at render when no value is passed.
All of the component's logic is **based around this assumption**. This means, that when the user begins typing their input, the component *"expects"* to have no items currently selected unless it was explicitly stated otherwise by the programmer. And when the user erases their input - *reverts the input field to its original state* - the component does the first logical thing - it reverts itself to the original state too. Which means - `selected === null` as of version `1.8.2`.

Needless to say, all of this logic is pretty far-fetched. There are cases we didn't account for when we were building this component. Things change, opinions change, new information comes.

And I'd be really glad to change this behviour instantly... but I can't, at least right now.

There would certainly be backwards-compatibility issues. So, for most cases, a simple `if` statement is not a very high price to pay.

I also don't see additional events necessary. This "simple-suggest" component has become very complex after 8 releases. Right now, I really don't see any need to exchange a little discomfort for even more complexity.

That being said, we will account for this issue in `v2.0`, which, I suppose, we'll have to release due to [huge breaking changes planned for Vue v3.0](https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf) in 2019. Which is soon anyway.

P.S. Thanks for a great issue.

**Comment by Raiondesu** [comment]
This connects to #108 in an oddly specific way...

**Comment by Raiondesu** [comment]
Wow, the big picture just hit me in a big way.

Expect this fixed in the next minor release (which is today).

**Comment by Raiondesu** [comment]
Since v1.9.0 the "null-selecting" behaviour will be consistent and regulated via a prop.
